// Generated by CoffeeScript 1.10.0
(function() {
  var Main;

  Main = (function() {
    function Main() {
      this.initAspect();
      this.initSlider();
      this.initEvents();
      this.update();
    }

    Main.prototype.initAspect = function() {
      var frame;
      frame = $('#main .frame');
      return frame.css('height', frame.width() * 9 / 16);
    };

    Main.prototype.initSlider = function() {
      var self;
      self = this;
      return $('#slider').slider({
        min: 0,
        max: 20,
        step: 0.1,
        value: 7,
        change: function(e, ui) {
          $('form .camera_h').val(ui.value);
          return self.update();
        },
        slide: function(e, ui) {
          $('form .camera_h').val(ui.value);
          return self.update();
        }
      });
    };

    Main.prototype.initEvents = function() {
      var self;
      self = this;
      $('form .floor_w').change(function() {
        var val;
        val = Number($(this).val());
        if (isNaN(val)) {
          val = 16;
          $(this).val(val);
        }
        $('#slider').slider({
          max: val * 5
        });
        $('form .floor_h').val(val * 9 / 16);
        return self.update();
      });
      $('form .floor_h').change(function() {
        var val;
        val = Number($(this).val());
        if (isNaN(val)) {
          val = 16;
          $(this).val(val);
        }
        $('form .floor_w').val(val * 16 / 9);
        return self.update();
      });
      $('form .wall_h').change(function() {
        var val;
        val = Number($(this).val());
        if (isNaN(val)) {
          val = 3;
          $(this).val(val);
        }
        return self.update();
      });
      return $('form .camera_h').change(function() {
        var val;
        val = Number($(this).val());
        if (isNaN(val)) {
          val = 10;
          $(this).val(val);
        }
        return self.update();
      });
    };

    Main.prototype.update = function() {
      var camera_h, floor_w, rate_inner, rate_outer, wall_h;
      floor_w = Number($('form .floor_w').val());
      wall_h = Number($('form .wall_h').val());
      camera_h = Number($('form .camera_h').val());
      rate_inner = (camera_h - wall_h) / camera_h;
      $('#main .floor').css('transform', "scale(" + rate_inner + ", " + rate_inner + ")");
      rate_outer = floor_w / (camera_h - wall_h) * Math.tan(65 / 360.0);
      return $('#main .wall').css('transform', "scale(" + rate_outer + ", " + rate_outer + ")");
    };

    return Main;

  })();

  $(function() {
    return new Main;
  });

}).call(this);
